name: Publish NuGet-Package

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true
  workflow_dispatch:

jobs:  
  publish_nuget:  
    uses: Abaddax/workflows/.github/workflows/dotnet.publish_nuget.yml@master
    with:
      CSPROJ_PATH: Abaddax.Utilities/Abaddax.Utilities.csproj
    permissions:
      contents: write
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
